# Generated by Django 5.1.5 on 2025-02-06 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcast_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='podcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast'),
        ),
    ]
