# Generated by Django 5.1.6 on 2025-02-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_episodio_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='criador',
        ),
    ]
