# Generated by Django 5.1.6 on 2025-02-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_podcast_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="foto",
            field=models.ImageField(
                default="user/static/user/img/user-default.jpg",
                upload_to="podcast/media/fotos",
            ),
        ),
    ]
