# Generated by Django 5.1.3 on 2025-02-22 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_podcast_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='data_envio',
        ),
        migrations.AddField(
            model_name='episodio',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='foto',
            field=models.ImageField(default='media/fotos/img/user-default.jpg', upload_to='media/fotos'),
        ),
    ]
