# Generated by Django 5.1.3 on 2025-02-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_remove_episodio_data_envio_episodio_data_publicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='usuario',
            new_name='criador',
        ),
    ]
